{% set version = "1.8.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dorng
  version: {{ version|replace("-", "_") }}

source:
  fn: doRNG_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/doRNG_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doRNG/doRNG_{{ version }}.tar.gz
  sha256: 8c84046970568a7b4eade1e5ba629f967cf061c8365a5e997e4f196688f11fab

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: doParallel, doMPI, doRedis, rbenchmark, devtools, knitr, bibtex, testthat
requirements:
  host:
    - r-base
    - r-foreach
    - r-iterators
    - r-rngtools >=1.5

  run:
    - r-base
    - r-foreach
    - r-iterators
    - r-rngtools >=1.5

test:
  commands:
    - $R -e "library('doRNG')"           # [not win]
    - "\"%R%\" -e \"library('doRNG')\""  # [win]

about:
  home: https://renozao.github.io/doRNG
  license: GPL-2.0-or-later
  summary: Provides functions to perform reproducible parallel foreach loops, using independent random streams as generated by L'Ecuyer's combined multiple-recursive generator [L'Ecuyer (1999), <DOI:10.1287/opre.47.1.159>]. It enables to easily convert standard %dopar% loops into fully reproducible loops, independently of
    the number of workers, the task scheduling strategy, or the chosen parallel environment and associated foreach backend.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
