{% set version = "1.8.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dorng
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/doRNG_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doRNG/doRNG_{{ version }}.tar.gz
  sha256: 0edff0a5b91772d6e0e61ae537cb505fa2be87a2cdc2e936e86cf2d8078e7c49

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach
    - r-iterators
    - r-rngtools >=1.5
  run:
    - r-base
    - r-foreach
    - r-iterators
    - r-rngtools >=1.5

test:
  commands:
    - $R -e "library('doRNG')"           # [not win]
    - "\"%R%\" -e \"library('doRNG')\""  # [win]

about:
  home: https://renozao.github.io/doRNG
  license: GPL-2.0-or-later
  summary: Provides functions to perform reproducible parallel foreach loops, using independent random streams as generated by L'Ecuyer's combined multiple-recursive generator [L'Ecuyer (1999), <DOI:10.1287/opre.47.1.159>]. It enables to easily convert standard %dopar% loops into fully reproducible loops, independently of
    the number of workers, the task scheduling strategy, or the chosen parallel environment and associated foreach backend.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
