{% set version = "1.7.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dorng
  version: {{ version|replace("-", "_") }}

source:
  fn: doRNG_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/doRNG_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/doRNG/doRNG_{{ version }}.tar.gz
  sha256: 27533d54464889d1c21301594137fc0f536574e3a413d61d7df9463ab12a67e9

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-foreach
    - r-iterators
    - r-pkgmaker >=0.20
    - r-rngtools >=1.2.4

  run:
    - r-base
    - r-foreach
    - r-iterators
    - r-pkgmaker >=0.20
    - r-rngtools >=1.2.4

test:
  commands:
    - $R -e "library('doRNG')"  # [not win]
    - "\"%R%\" -e \"library('doRNG')\""  # [win]

about:
  home: https://renozao.github.io/doRNG
  license: GPL (>= 2)
  summary: Provides functions to perform reproducible parallel foreach loops, using independent
    random streams as generated by L'Ecuyer's combined multiple-recursive generator
    [L'Ecuyer (1999), <DOI:10.1287/opre.47.1.159>]. It enables to easily convert standard
    %dopar% loops into fully reproducible loops, independently of the number of workers,
    the task scheduling strategy, or the chosen parallel environment and associated
    foreach backend.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
