travis:
  secure:
    BINSTAR_TOKEN: xQawrHLC8UVUHHU0OHqOcWkG3zXEgCqRvRhtChX57sWRtUqoaPYemwXiYSsu8L/hTGfth+hXR5bEqmj2e8plOddIW/yPeQbIZMYD2CAwsI3ZKD/Qf05bDlsYNmRRrOkPBZYEcSp0sqIjLfg8gVloEtLBitlDcokzt0mrd+m5MFy+8y9mf4MAwymgKjlDu482awgei0kh5fFEAbg43M7qi6/rUAkjZcnZwrtoXkpMg1fVFkyQIKeXzQXCCuMQaAJ7Lj6xH86DA5IIQrMR33yz775jVYl8bxof35QVBzYGeSSyrp5ON041Nc9VSyKLGLbs3ppiBUL0voNA8VnLBUD+aS0mjuo6ChSWZy96cRktSKT2J57uHyHfiqbeC1Sb4lvC1ffoqQ+oTn70EkOx5tcvh+dzSPRJnJLGIRGFMwSBylbMBXkYgZfcDaT1rz+ec3/QdU9/d6UyV0l78lwK2/BF85iuweAwc1WEMqKO2kZjVo0gns+bAa22rVFB+LqOxKCm3vLRHo00riflCqtYPIXdyEsa3WimlXYz035UFxMugCeVXIXy0FqiqSqFcsdMWQGe05kWYJER4OGadZ8WK60x9U9bWLIRA6nF/XB+uIvmgZpodKx1TpEqSbaZAV52/RgWizlM9g4t51mPApsX9Rr26bWhiJkeG0ZQ3qepCGtW3Tg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
