appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: 0nYhCeKCYLxedRlZYAox+cTPrgB4H8E6q7UKQ4RL3l8jhwZeGV7tSLhaYhbszu6MQFIsNMiBB8gRS7XMoKcCw5Xv3EaqNTVyszWRrbU3xtu4EPhkY9sAWTqBrTLDDj9bHWQRtXzt/+TuSFrvL9s5G/s9BYeXVUQqxftrqMScaot3jOPqkSPTEyLtZ0sITbvoFQsPiXVVZOKFg2Da9Y/TU95XI54vYiZ4lXJRImVnmvwOhzFue/LyY/bvnSVU95nDPDspmxwBeKfPjctHXt+fqnvGWbvNfNax1MFwF9q8bJbajV5b9BcfUYNglUvk/9gG8McqviadNrGPUbZemOWmc9uXy/vhnROilmOgFrmy4G//5X+VEeVNPOIRn24mkwLjdUdle7K61lPUKhKnE83ezxqYzNKBO/nOG6qRaZbqpHfKb/TQN8vmX+uWl3x6HMTcp63zFAxhaBlmJ8stP9Q+3MWHNkVi0+RaM68+cAAYjHfsXzyGHu0CMAov0T8E/XqFgNeEKp42QgzwZaZPE7fT6g9OWU+Ioz85nLGbrQ0bOc+a6eppSEYD4DWzy1zahLIo1/wiI8u7ADm6X2hW2K5gQWuhakWwNoiXAc5W+fAxvcfIkNY+iiX/lL1GP7lO8GV4PSvBL6whKakRJNru0ZmkmRD/ZHYtwQV0PzMdhj+vyRU=}
